Repository zonemaster/zonemaster-ldns, pull requests merged in 2020-04, with the labels that each got.

#103 Corrected locale dependent unit test t/idn.t
  t/idn.t
Labels: A-UnitTests, T-Bug

#105 Update supported Perl versions in Travis
  .travis.yml
Labels: A-Travis

#93 Updates in prepartion for release v2019.2
  Changes
  lib/Zonemaster/LDNS.pm
Labels: A-Documentation, P-High
